version: '3.3'

services:
   mariadb:
    image: mariadb  
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MdbSql@123
      MYSQL_DATABASE: defaultdatabase
      MYSQL_USER: User123
      MYSQL_PASSWORD: Pwd123

   dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8181:80"
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      PMA_USER: User123
      PMA_PASSWORD: Pwd123
